### PR TITLE
Improve "hash brownies" example and explanation

### PR DESCRIPTION
**Pull request by jab**
I found the current "hash brownies" example and explanation confusing, so I'm proposing these changes.

This is clearer because it focuses on *equivalence* as the key principle first, without muddying the waters with hashing and immutability up front.

Once this does mention hashing, it explains it in the context of being a performance optimization (which is all it is), not as something that is central to what containment in a dict actually means.

Hope this helps!

### CODE REVIEW

**Comment by cclauss** [comment]
Resolve conflicts?

**Comment by jab** [comment]
I'll leave it up to @satwikkansal, whose 7b22f84f97723b5b8b49435a5810c37bcbbbd582 (in response to my #77) landed before this did with overlapping intent.

**Comment by satwikkansal** [comment]
Sorry, totally forgot about this PR. Addressed this PR in the recent commit https://github.com/satwikkansal/wtfpython/commit/185d60c1b696e2029f7e6d641afe272ca466feec, I think it can be closed now.

**Comment by matkoniecz** [comment]
> I think it can be closed now.

In such case I would recommend closing it.

**Pull request closed without merging**
