### PR TITLE
#347: Add markdownlint-cli2 as Github Action and pre-commit hook

### LINKED ISSUE #347: Add markdown linter and formatter
Current `README.md` does not follow any `markdown` convention formats. The project should choose a `markdown` flavor and stick to it with the help of linter/formatter

### PR DESCRIPTION
**Pull request by nifadyev**
Resolves #347

`pre-commit` will be properly set up after #350 is merged

@satwikkansal , please analyze the `markdownlint-cli2` output and decide, what errors are better to ignore

[sample Github action output](https://github.com/nifadyev/wtfpython/actions/runs/11475042864/job/31932112062?pr=2)

Errors frequency for current `README.md`:
- 303 MD013 - Line length (expected 80)
- 254 MD004 - Unordered list style [Expected: dash; Actual: asterisk]
- 177 MD031 - Fenced code blocks should be surrounded by blank lines
- 67 MD026 - Trailing punctuation in heading [Punctuation: '!']
- 62 MD024 - Multiple headings with the same content [Context: "💡 Explanation:"]
- 39 MD032 - Lists should be surrounded by blank lines
- 30 MD012 - Multiple consecutive blank lines [Expected: 1; Actual: 2]
- 23 MD022 - Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below]
- 22 MD009 - Trailing spaces [Expected: 0 or 2; Actual: 5]
- 14 MD034 - Bare URL used
- 9 MD040 - Fenced code blocks should have a language specified
- 8 MD036 - Emphasis used instead of a heading [Context: "Output"]
- 7 MD007 - Unordered list indentation [Expected: 2; Actual: 4]
- 3 MD030 - Spaces after list markers [Expected: 1; Actual: 2]
- 2 MD001 - Heading levels should only increment by one level at a time [Expected: h2; Actual: h3]
- 2 MD014 - Dollar signs used before commands without showing output [Context: "$ wtfpython"]
- 2 MD038 - Spaces inside code span elements [Context: "`(a, 9) `"]
- 2 MD029 - Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/1/1]
- 2 MD049 - Emphasis style [Expected: asterisk; Actual: underscore]
- 1 MD041 -  First line in a file should be a top-level heading
- 1 MD051 - Link fragments should be valid [Context: "[[More content like this?](about:blank#more-content-like-this)](#more-content-like-this)"]
- 1 MD019 - Multiple spaces after hash on atx style heading [Context: "####  💡 Explanation:"]
- 1 MD027 - Multiple spaces after blockquote symbol [Context: "    >  If sep is not specified..."]

### CODE REVIEW

**Comment by satwikkansal** [comment]
Hi @nifadyev, let's ignore MD026, MD024, MD034, rest of all look reasonable to me, your thoughts?

**Comment by nifadyev** [comment]
I agree with you, except `MD034` - most URLs should be hidden using `[]()` Markdown format. And `MD033` should probably be ignored as well, html is used for image formatting and changing it based on light/dark theme

**Comment by satwikkansal** [comment]
> I agree with you, except MD034 - most URLs should be hidden using []() Markdown format.

Yes, but sometimes it's okay to have them displayed in raw format, when I want the site to be attributed transparently, because otherwise we have to un-necesarily explain where the link directs.

> And MD033 should probably be ignored as well, html is used for image formatting and changing it based on light/dark theme

There was no mention of MD033 in the report in first comment, but yes, having HTML is okay.

> Is line length set to 80 OK to you?

I prefer higher length like 120 or 140.

> I'd prefer to format them gradually, making PRs with no more than 500 changed lines. It will ease review and reduce missing errors

I'd say fix everything in 1 go with autofix, and then whatever can't be fixed we can do incremental fixes.

**Comment by nifadyev** [comment]
Agreed on ignored rules and how to format files. I will make changes in this PR soon

**Comment by nifadyev** [comment]
Hey @satwikkansal , I've used autofix to format `README.md`. Now there are 268 errors and most of them - line lengths. I guess they should be fixed separately.

**Review by satwikkansal — APPROVED** [review]
@nifadyev Looks good! Let's change the base to dev and merge.

**Comment by nifadyev** [comment]
@satwikkansal , base branch has been changed to `dev`

**Comment by satwikkansal** [comment]
Merged 🚀

**Pull request merged**
