### PR TITLE
Fix type

### PR DESCRIPTION
**Pull request by Xdminsy**

### CODE REVIEW

**Comment by satwikkansal** [comment]
Thanks @Xdminsy , merged it 👍

**Comment by Xdminsy** [comment]
Oh I found I made a typo in commit message(typo -> type) when fixing a typo, how embarrassing, sorry for that.

**Comment by satwikkansal** [comment]
Haha, happens. Don't worry about it, I fixed your typo in the commit while squashing and merging. So let's keep this a secret :p

**Comment by Xdminsy** [comment]
Haha, great, thank you for that.

**Pull request merged**
