### PR TITLE
Test Travis

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
On https://travis-ci.com/satwikkansal/wtfpython do __More options__ and then __Trigger build__...  Does that work?

**Comment by cclauss** [comment]
If all that looks good, go to https://github.com/settings/installations and click __Applications__ and make sure __Travis CI__ is there and has access to this repo.

**Comment by cclauss** [comment]
Normally this stuff just works.

https://travis-ci.com/satwikkansal/wtfpython/requests Is interesting because your Trigger builds are getting registered but the builds are not running.

**Comment by cclauss** [comment]
The “no commit available” message on https://travis-ci.com/satwikkansal/wtfpython/requests makes me thinks that Travis CI does not have access to this repo in https://github.com/settings/installations __Applications__.

**Comment by cclauss** [comment]
Cycle thru the __More options__ at https://travis-ci.com/satwikkansal/wtfpython/settings especially the __Requests__ and __Trigger build__.  When you trigger a build, is a new request created?

**Comment by satwikkansal** [comment]
Figured out the [issue](https://blog.travis-ci.com/2019-01-31-github-services-integration-deprecation)

Migrating to newer github integrations from the travis dashboard did the job for me. Here's the first build https://travis-ci.com/satwikkansal/wtfpython/jobs/213767714 

Thank you so much!

**Pull request closed without merging**
