### PR TITLE
#193 The out of scope variable, nonlocal

### PR DESCRIPTION
**Pull request by diptangsu**
I did not have to make many changes to what was already present with `global`. The link to the blog also is the same since it also explains `nonlocal`.

Also, this is something I did not understand, you can modify this bit before merging if at all this PR is merged.
image

### CODE REVIEW

**Comment by satwikkansal** [comment]
Hi @diptangsu 

Example Id is any randomly generated UUID.

Regarding the example part, thanks for the work. I think it'd be better if we can add `nonlocal` snippet to the existing example (if you see there's a lot of redundancy in the explanation, which people don't usually like).

**Comment by satwikkansal** [comment]
I think it's enough to mention the nolocal keyword in the explanation with (probably) an example snippet

**Comment by diptangsu** [comment]
Yes, I agree!
Let me change the original example to add the nonlocal part. I actually thought about it but I didn't know how you'd feel about me changing an existing example.

**Comment by diptangsu** [comment]
Tried my best to fit it in with the existing example. Let me know if you want me to change something.

**Comment by satwikkansal** [comment]
Hi @diptangsu 

Thanks, there are a few minor change, but don't worry, I'll add those myself on top of your commit. Merging your PR for now.

**Pull request merged**
