### PR TITLE
Add Russian translation

### LINKED ISSUE #297: Add translation for Russian
Expected time to finish: 2 weeks. I'll start working on it from next week.

### PR DESCRIPTION
**Pull request by nifadyev**
Translation is adaptive (not word-to-word) and it tries to save the original meaning.

As discussed with @satwikkansal, this translation (and possibly all existing ones) will be stored in folder inside original repository, not in fork. It will give more control because everything will be stored in 1 repository, and it eliminates possible deletion or making translation private.

Please feel free to review this PR. The PR will be periodically updated with new commits. 1 commit — 1 example

Resolves #297

### CODE REVIEW

**Comment by nifadyev** [comment]
Hey @satwikkansal , sorry for a long delay, I had some motivation issues, but now I've finished translation and making some sanity check. It is not wise to read the whole document with ~4000 lines of code, so i will complete working on this PR in next few days and let you know
Meanwhile, I'd love to take part in next release, even in some minor role (e.x. checking examples, organize repo by labeling issues, closing irrelevant and moving some of them to discussions)

**Comment by satwikkansal** [comment]
Hey @nifadyev that's great news! I've been observing consistent commits from you over last few days, I hope you had fun working on the translation :) 

And yes, feel free to let me know once you've finished the sanity check. I'll merge your branch! 

I'll keep you in the loop about the next iteration, we can work together on that one.  

cc @Elkiwa (also interested in working together on next release iteration)

**Comment by nifadyev** [comment]
Good day @satwikkansal . I've finished minor refactoring and checking, and I believe the translation is ready to be merged. 

I've also translated `CONTRIBUTING` and `CONTRIBUTORS` pages but not `code-of-conduct` . Should it be translated as well? It has official russian [translation](https://www.contributor-covenant.org/ru/version/2/0/code_of_conduct/) but for 2.0 version. But `wtfpython` has 1.4 version

**Comment by satwikkansal** [comment]
Good day @nifadyev 

Thanks! I'll merge the PR. Regarding code-of-conduct, let's use version 2.0 and use the official translation. Could you make these changes as well in your PR?

**Comment by nifadyev** [comment]
Hey @satwikkansal , Code of Conduct translation is done

**Comment by satwikkansal** [comment]
Hi @nifadyev 

This changes the primary translation in Contributors.md and other two files from English to Russia. 

I'd suggest we create a directory named `ru-russian` inside the `translations` directory, where we can move these translated files, and we leave the original one in the root in English.

Could you please make that change?

**Comment by nifadyev** [comment]
Whew, that was a challenging task to fix the files and found minor issues in PR but I hope it is fine now

**Comment by satwikkansal** [comment]
Thanks for all your efforts @nifadyev, this looks great!! 

Merging it now 🚀

**Comment by nifadyev** [comment]
Awesome, thank you, @satwikkansal . Looking forward to next tasks)

**Comment by nifadyev** [comment]
One more minor fix - main README contains link to old translation. Should I make small PR or you can make it directly to master? The correct link is `https://github.com/satwikkansal/wtfpython/tree/master/translations/ru-russian`

**Comment by satwikkansal** [comment]
Yes please, let's do that! @nifadyev

**Comment by nifadyev** [comment]
The PR is #334

**Pull request merged**
